name: videoplayerdemo
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^1.0.0
  video_player: ^1.0.0
  cupertino_icons: ^0.1.3
  open_iconic_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  assets:
    - assets/images/speed.jpg